name: Matrix Strategies
on:
    push:
        branches:
            - main
            - dev
jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                node-version: [16, 18]
        continue-on-error: true
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get the Code
              uses: actions/checkout@v6
            - name: Install Nodejs
              uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.node-version }}
