name: A Test Workflow
on: push
jobs:
    test_react_operation:
        runs-on: ubuntu-latest
        steps:
            - name: Get the Code
              uses : actions/checkout@v6
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm test